apiVersion: v1
data:
  settings.yml: "use_default_settings: true\n\ngeneral:\n  instance_name: \"searxng-local\"\n\nsearch:\n\
    \  safe_search: 0\n  formats:\n    - html\n    - json\n\nserver:\n  secret_key: \"changeme-searxng-secret-key-i8labs\"\
    \n  limiter: false\n  image_proxy: false\n\nui:\n  static_use_hash: true\n\noutgoing:\n  request_timeout:\
    \ 3.0\n  max_request_timeout: 6.0\n\nengines:\n  - name: duckduckgo\n    disabled: true\n  - name:\
    \ wikidata\n    disabled: true\n"
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: default

