apiVersion: node.k8s.io/v1
handler: nvidia
kind: RuntimeClass
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQvW7rMAyFX+XizIovHMOJI6BD0bFbh+6URNeqbSowFRdF4HcvhGbo0p+R+MiPh7yCzvGZF41JYCEpcDV2WsX0f61hMJCEiZeC1hgiwWCMEmDxdJEcZ36YSBUGM2cKlAn2ChJJmXJMoqVM7pV9Vs7VElPlKeeJy4JYNDDf8vQmvOxe1hEWY6NfyFqbf49Rwt19CEl+VQjNDIvlM7H+qV/P5MvQeHG803fNPGMzmMjx9ONVA+kAi/a4b2rHdDq0ne/3be8D+X3T1749dC35o3O+P3VNkd7y3T68bR8BAAD///Uj4MeVAQAA
    objectset.rio.cattle.io/id: ''
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: runtimes
    objectset.rio.cattle.io/owner-namespace: kube-system
  labels:
    objectset.rio.cattle.io/hash: 57231bea9658cf25fcdac23f1c5685ac7bbcf983
  name: nvidia

